

"""
Django settings for nss project.
Generated by 'django-admin startproject' using Django 5.1.4.
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Static files configuration
STATIC_DIR = os.path.join(BASE_DIR, 'static')

# Quick-start development settings - unsuitable for production
SECRET_KEY = 'my_secret_key'  # Consider using environment variable in production

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # Changed to False for production

# Updated ALLOWED_HOSTS for your PythonAnywhere domain
ALLOWED_HOSTS = [
    'iwasbinod.pythonanywhere.com',
    'www.iwasbinod.pythonanywhere.com',
    '127.0.0.1',
    'localhost'
]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'nssapp',
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'nss.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.csrf',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nss.wsgi.application'

# Database configuration for PythonAnywhere
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        # 'NAME': 'iwasbinod$default',  # PythonAnywhere database name format
        'NAME':'nss_db',               #  used  schema name here
        'USER': 'root',
        'PASSWORD' : 'root',
        'HOST': '',
        # 'USER': 'iwasbinod',         # Your PythonAnywhere username
        # 'PASSWORD': 'nssroot@123',          # Your MySQL password
        # 'HOST': 'iwasbinod.mysql.pythonanywhere-services.com',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        }
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
# TIME_ZONE ='Asia/Kathmandu'
USE_I18N = True
USE_TZ = True

# Static files configuration for PythonAnywhere
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

# Static root for collectstatic
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'nssapp.User'

# Email configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'dc.aloneboe@gmail.com'
EMAIL_HOST_PASSWORD = 'dhfs fyjd fdjc wsfu'
DEFAULT_FROM_EMAIL = 'dc.aloneboe@gmail.com'

# Forgot password settings
MY_SITE_DOMAIN = "iwasbinod.pythonanywhere.com"  # Updated to your domain
MY_SITE_PROTOCOL = "https"  # Changed to https for production

# Site ID
SITE_ID = 1

# Security settings for production
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Session settings
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True


########################################
#################################

# settings.py - Add these settings
# settings.py - Better approach with environment variables
import os

# Google OAuth2 Configuration
GOOGLE_OAUTH2_CLIENT_ID = os.environ.get(
    'GOOGLE_OAUTH2_CLIENT_ID', 
    '348432816403-91ghfpoc20u6ruog0vg73lvsf6ti3hhg.apps.googleusercontent.com'
)
GOOGLE_OAUTH2_CLIENT_SECRET = os.environ.get(
    'GOOGLE_OAUTH2_CLIENT_SECRET',
    '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'
)

# Dynamic settings based on environment
if DEBUG:
    GOOGLE_OAUTH2_REDIRECT_URI = 'http://127.0.0.1:8000/note/auth/google/callback/'
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
    print("=== DEVELOPMENT MODE ===")
else:
    GOOGLE_OAUTH2_REDIRECT_URI = 'https://iwasbinod.pythonanywhere.com/note/auth/google/callback/'
    ALLOWED_HOSTS = ['127.0.0.1','iwasbinod.pythonanywhere.com']
    print("=== PRODUCTION MODE ===")











####################################
####################################
# 3

# """
# Django settings for nss project.

# Generated by 'django-admin startproject' using Django 5.1.4.

# For more information on this file, see
# https://docs.djangoproject.com/en/5.1/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.1/ref/settings/
# """
# import os
# from pathlib import Path

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent

# #static folder ko lagi yei paste garda vyo
# STATIC_DIR=os.path.join(BASE_DIR, 'static')
# #

# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!

# SECRET_KEY = 'my_secret_key'


# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# # ALLOWED_HOSTS = []

# import os

# ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")


# # ===================imp=========================
# # In production → set an env variable:
# # export DJANGO_ALLOWED_HOSTS="mydomain.com,www.mydomain.com"
# # ===================imp=========================



# # Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'nssapp',
#     # 'django.contrib.sites',
#     # 'allauth',
#     # 'allauth.account',
#     # 'allauth.socialaccount',
#     # 'allauth.socialaccount.providers.google',
# ]

# AUTHENTICATION_BACKENDS = [
#     'django.contrib.auth.backends.ModelBackend',
#     # 'allauth.account.auth_backends.AuthenticationBackend',
# ]



# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
#     # 'allauth.account.middleware.AccountMiddleware',
# ]

# ROOT_URLCONF = 'nss.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': ['templates'],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 "django.template.context_processors.csrf",
#                 "django.template.context_processors.media",
#                 "django.template.context_processors.static",
#                 "django.template.context_processors.tz",
            
#                 'django.contrib.messages.context_processors.messages',
               
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'nss.wsgi.application'


# # Database
# # https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.sqlite3',
# #         'NAME': BASE_DIR / 'db.sqlite3',
# #     }
# # }
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'nss_db',               #  used  schema name here
#         'USER': 'root',              #  MySQL username
#         'PASSWORD': 'root', #  MySQL password
#         'HOST': '127.0.0.1',
#         'PORT': '3306',
#         'OPTIONS': {
#             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
#         }
#     }
# }


# # Password validation
# # https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/5.1/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.1/howto/static-files/

# # STATIC_URL = 'static/'
# # #yo pani last tirw yo chia jaha static_url xa tei tira

# # STATICFILES_DIRS=[
# #     STATIC_DIR
# # ]
# #


# STATIC_URL = '/static/'
# import os
# STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]


# # Default primary key field type
# # https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# AUTH_USER_MODEL = 'nssapp.User'


# #
# MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / 'media'


# # settings.py
# SITE_ID = 1  # Ensure this is set
# #email login sys
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'dc.aloneboe@gmail.com'
# EMAIL_HOST_PASSWORD = 'dhfs fyjd fdjc wsfu '
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# #forgot pass

# DEFAULT_FROM_EMAIL = "MyApp <dc.aloneboe@gmail.com>"
# MY_SITE_DOMAIN = "127.0.0.1:8000"   # change to yourdomain.com in production
# MY_SITE_PROTOCOL = "http"           # use "https" in production



# # 
# # 
# # social login seting


# #Social login settings

# # SOCIALACCOUNT_PROVIDERS = {
# #     'google': {
# #         'APP': {
# #             'client_id':'348432816403-91ghfpoc20u6ruog0vg73lvsf6ti3hhg.apps.googleusercontent.com',
# #             'secret': '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',
          
# #         },
# #         'SCOPE': ['profile','email',],
# #          'AUTH_PARAMS': {'access_type': 'online'},
# #         'METHOD': 'oauth2',
# #         'VERIFIED_EMAIL': True,
# #     },
   
   
# # }



# # SOCIALACCOUNT_LOGIN_ON_GET = True
# # LOGIN_REDIRECT_URL = 'dashboard/'  # Redirect to dashboard after login


# # #  IMPORTANT: Skip the intermediate page
# # SOCIALACCOUNT_LOGIN_ON_GET = True  # This bypasses the 3rd-party signup page!
# # SOCIALACCOUNT_AUTO_SIGNUP = True   # Auto-create accounts without intermediate form

# # # Optional but recommended
# # ACCOUNT_LOGOUT_ON_GET = True
# # SOCIALACCOUNT_STORE_TOKENS = True


# # # # Email handling
# # # ACCOUNT_EMAIL_REQUIRED = True
# # # ACCOUNT_EMAIL_VERIFICATION = 'optional'  # or 'none' for no verification


# # 

# # new

# # import os
# # from dotenv import load_dotenv

# # # Load environment variables from .env file
# # load_dotenv()

# # # SECURITY WARNING: keep the secret key used in production secret!
# # SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-default-key-for-dev')

# # # SECURITY WARNING: don't run with debug turned on in production!
# # DEBUG = os.environ.get('DEBUG', 'True') == 'True'










# # # Social login settings - SIMPLIFIED VERSION
# # SOCIALACCOUNT_PROVIDERS = {
# #     'google': {
# #         # # 
# #         # 'APP': {
# #         #     'client_id': os.environ.get('GOOGLE_OAUTH_CLIENT_ID', ''),
# #         #     'secret': os.environ.get('GOOGLE_OAUTH_CLIENT_SECRET', ''),
# #         # },
# #         # # 
# #         'SCOPE': ['profile', 'email'],
# #         'AUTH_PARAMS': {'access_type': 'online'},
# #     }
# # }

# # # Remove the APP section from SOCIALACCOUNT_PROVIDERS - configure in admin instead
# # SOCIALACCOUNT_LOGIN_ON_GET = True
# # SOCIALACCOUNT_AUTO_SIGNUP = True
# # ACCOUNT_LOGOUT_ON_GET = True
# # SOCIALACCOUNT_STORE_TOKENS = True

# # LOGIN_REDIRECT_URL = '/note/dashboard/' # Remove trailing slash - use URL name
