# Generated by Django 5.2.3 on 2025-07-01 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nssapp', '0003_notes_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_code',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_code',
        ),
    ]
