# Generated by Django 5.2.3 on 2025-09-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nssapp", "0005_comment_upvote"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="google_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
