# Generated by Django 5.2.3 on 2025-10-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nssapp", "0007_exclusivenote_notepurchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
