# Generated by Django 5.2.3 on 2025-10-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nssapp", "0007_exclusivenote_notepurchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="notepurchase",
            name="esewa_transaction_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="notepurchase",
            name="esewa_transaction_uuid",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="notepurchase",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
