# Generated by Django 5.1.4 on 2025-06-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nssapp', '0002_alter_notes_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='category',
            field=models.CharField(choices=[('BE_COMPUTER', 'BE COMPUTER'), ('BBA', 'BBA'), ('BCA', 'BCA'), ('BE_CIVIL', 'BE CIVIL'), ('MBA', 'MBA'), ('PLUS_TWO', '+2'), ('OTHERS', 'Others')], default='BE_COMPUTER', max_length=20),
        ),
    ]
